### PR TITLE
Allow fonts to be pulled

### PR DESCRIPTION
**Pull request by waldermort**
The config file doesn't allow for font file (bootstrap, fontawesome etc) URLs to be served.

### CODE REVIEW

**Comment by andrerom** [comment]
+1, ping @dpobel

**Comment by waldermort** [comment]
ping @andrerom @dpobel  jira issue logged and rebased

**Comment by dpobel** [comment]
+1

**Comment by andrerom** [comment]
Thanks @waldermort, nice :)

**Comment by andrerom** [comment]
Hmm, we probably need to adjust the nginx config as well now, right @yannickroger ?

**Comment by yannickroger** [comment]
Looks like we do: https://github.com/ezsystems/ezpublish-community/blob/master/doc/nginx/etc/nginx/ez_params.d/ez_prod_rewrite_params#L5

**Comment by andrerom** [comment]
@waldermort Up for it? If so it will be the same issue, will handle them together.

**Pull request merged**
