### PR TITLE
Suggestion: Use global namespaces in EzPublishKernel 

### PR DESCRIPTION
**Pull request by xrow**
Use global namespaces in EzPublishKernel for adding Bundles. This looks easier to handle.

### CODE REVIEW

**Comment by jeromegamez** [comment]
:+1: for this one for the following reasons:

- When programmatically adding a new bundle with `ezpublish:console generate:bundle` a new line containing the new bundle's full namespace will be inserted, which creates an inhomogeneous  picture (some bundles with, some without the full namespace)
- With the full namespace, it is easier to see where a bundle is coming from
- When removing a bundle, one would just have to remove one line instead of two (the bundle line and the `use …`line
- The file gets shorter :smile:

**Comment by jeromegamez** [comment]
@xrow One additional note: as the `EzPublishKernel` is in the global namespace, it is not necessary to prefix every Bundle with a `\`.

**Comment by brookinsconsulting** [comment]
ping @jeromegamez @xrow @crevillo 

What was the result of this discussion? Was a clear consensus reached?

Is this PR still valid and under consideration for merging?

Cheers,
Brookins Consulting

**Comment by andrerom** [comment]
It will need to be rebased and also one needs to be created against ezplatform.

I'm +1 on this when that is fixed, given the original issue of not being able to use add bundle command right. /cc @bdunogier @lolautruche

**Comment by joaoinacio** [comment]
See updated and rebased PRs for community and ezplatform.

**Pull request closed without merging**
