### PR TITLE
Updated the dependency to PlatformUIAssetsBundle to version 0.2

### PR DESCRIPTION
**Pull request by dpobel**
For https://jira.ez.no/browse/EZP-21265 / https://github.com/ezsystems/PlatformUIBundle/pull/168 to get the changes introduced in https://github.com/ezsystems/ez-js-rest-client/pull/53

### CODE REVIEW

**Comment by andrerom** [comment]
+1, seems travis is having major performance issue, so guess we can merge this despite travis.

**Comment by dpobel** [comment]
A test is now failing on Travis, but this is unrelated to this change, the master happens on master as well: https://travis-ci.org/ezsystems/ezpublish-community

**Comment by andrerom** [comment]
yes, and don't seem to be any changes in DemoBundle, so maybe caused by something in kernel.

**Comment by bdunogier** [comment]
Yes, it is an error in kernel (probably). Master is now failing as well (https://travis-ci.org/ezsystems/ezpublish-community/jobs/50119945), unsure why as of now.

**Pull request merged**
