### PR TITLE
Fix EZP-24465: Bump Symfony requirement to v2.7

### PR DESCRIPTION
**Pull request by lolautruche**
> https://jira.ez.no/browse/EZP-24465

See https://github.com/ezsystems/ezpublish-kernel/pull/1221
See https://github.com/ezsystems/ezplatform/pull/21

### CODE REVIEW

**Comment by lolautruche** [comment]
Review ping @andrerom @bdunogier @dpobel @yannickroger @pspanja @glye

**Comment by andrerom** [comment]
+1 but we seem to again have  conflict on Demo Bundle.

@bdunogier should we rather depend on a certain tag of Demo Bundle for this repo? I did try depending on 5.4 for DemoBundle *(I think)*, but that did not work that much better if I remember correctly.

**Comment by lolautruche** [comment]
The problem here doesn't seem to come from DemoBundle, but from `ezsystems/repository-forms` being absent from main `composer.json` because of minimum stability.

**Comment by andrerom** [comment]
ok

**Comment by lolautruche** [comment]
Travis is failing with demo content test. Behat is complaining that "mount fuji" image cannot be found.
This is completely unrelated to this PR and already appeared for others PRs (see #217 for example). Demo content updated and not behat tests? ping @joaoinacio 

Other than that, this PR should be fine.

**Comment by andrerom** [comment]
ah yes, it's the difference in markup between legacy stack and platform stack in regards to images.

**Pull request merged**
