### PR TITLE
Bump Symfony requirement to ~2.6

### PR DESCRIPTION
**Pull request by lolautruche**
See https://github.com/ezsystems/ezpublish-kernel/pull/1111

Also fixed PHP requirement. Now in sync with ezpublish-kernel

### CODE REVIEW

**Comment by masev** [comment]
Hi, this fix is not in 5.4.1 ? Maybe it should be ?

**Comment by andrerom** [comment]
Could you be more specific? the changes should be there, see update instructions on the release notes:
https://doc.ez.no/display/EZP/5.4.1+Release+Notes

**Comment by masev** [comment]
If I install 5.4.1 and I update Symfony to 2.6.1 as mentioned here : https://doc.ez.no/display/EZP/5.4.1+Release+Notes then I have the following vendors : 
 - SF 2.6
 - ezpublish-kernel v2014.11.8

But ezpublish-kernel v2014.11.8 doesn't have the fix (https://github.com/ezsystems/ezpublish-kernel/pull/1111) that makes it works with SF2.6 or at least I couldn't find it here : https://github.com/ezsystems/ezpublish-kernel/commits/v2014.11.8

**Comment by andrerom** [comment]
wtf, ping @lolautruche

**Comment by andrerom** [comment]
@masev did you start with a 5.4.0 install or a 2014.11 install?

**Comment by masev** [comment]
Indeed I started with a 2014.11 (=5.4) and then updated to the last 2014.11.x (=5.4.1)

**Comment by andrerom** [comment]
Ok, well actually 2014.11 <> 5.4, and 2014.11.x  <> 5.4.1, so that explains it.
For eZ Publish, 4.x and 5.x are EE versions, they are separate releases with usually full LTS maintenance and support.

This will hopefully be a bit easier this year with eZ Platform, as they will have the same releases, but eZ Studio is only available for EE customers.

If you do have subscription for EE for this site in question, then download 5.4 install (or at least it's composer.json), setup authentication for updates.ez.no via your service portal and do the 5.4.1 update as documented on release notes.

**Comment by masev** [comment]
Yes I know, but I was talking in community equivalent, sorry for the
misunderstanding :)

OK but, when using community, the problem is still here when you update to
the last 2014.11.x, no ?

Le 29 janv. 2015 18:29, "André R." <notifications@github.com> a écrit :
>
> Ok, well actually 2014.11 <> 5.4, and 2014.11.x <> 5.4.1, so that
explains it.
> For eZ Publish, 4.x and 5.x are EE versions, they are separate releases
with usually full LTS maintenance and support.
>
> This will hopefully be a bit easier this year with eZ Platform, as they
will have the same releases, but eZ Studio is only available for EE
customers.
>
> If you do have subscription for EE for this site in question, then
download 5.4 install (or at least it's composer.json), setup authentication
for updates.ez.no via your service portal and do the 5.4.1 update as
documented on release notes.

**Comment by andrerom** [comment]
I think so, @lolautruche would know, he is back online tomorrow afaik.

**Comment by lolautruche** [comment]
@masev I don't understand what's the issue here. Just update your `composer.json`, run a composer update and you're done!

**Comment by masev** [comment]
The problem is that with the last 2014.11.x if we follow the upgrade steps
for 5.4.1, that is to say update to SF 2.6 then it's not working anymore
because the wrong kernel version is loaded.

But maybe there is no problem and we just shouldn't update Symfony with the
last 2014.11.x ? (I thought it was equivalent to 5.4.1)
Le 29 janv. 2015 18:59, "Jérôme Vieilledent" <notifications@github.com> a
écrit :

**Comment by andrerom** [comment]
but 5.4.1 is about updating from 5.4.0, so please wait for 2015.01 for symfony 2.6 version.

**Comment by bdunogier** [comment]
5.4.1 and 2014.11 can't be equivalent, as 5.4.1 was frozen more than a month later.

On 2014.11, you can either wait for 2015.01 like André said (it will be soon, maybe next week), or cherry-pick the changes from master that add support for Sf 2.6.

**Comment by masev** [comment]
I sum up what was my problem if someone got the same issues because I wasn't clear enough before (sorry) : 
 - I installed a fresh Community v2014.11.1 (I got SF2.5 and ezp-kernel v2014.11.6)
 - I run a composer update (I wanted to get the ESI patch) and because of composer requirements "~2.5" I bumped to SF2.6 and ezp-kernel v2014.11.8 (I still think there is a composer requirements issue here ...)
 - It's not working anymore because ezp-kernel v2014.11.8 doesn't have the SF2.6 patch
 - I applied this patch to fix the issue : https://github.com/ezsystems/ezpublish-community/commit/11e5cf675af3872c448cc6f0739844398ace2546

@lolautruche @bdunogier @andrerom I'll wait for 2015.01 then. Thank you !

**Comment by bdunogier** [comment]
Thank you !

The fact that you did receive an update to a non-working 2.6 is an issue, and could/should have been fixed by releasing a 2014.11.2 that restricts Sf to ~2.5.0.

**Pull request merged**
