### PR TITLE
Fix EZP-24311: Clarify the differences between ezpublish-community and ezplatform repositories in README.md documentation

### PR DESCRIPTION
**Pull request by brookinsconsulting**
Hello,

Related issue for these pull requests: https://jira.ez.no/browse/EZP-24311

Per request from Andre to update the repository README.md documentation to clarify the differences between the older ezpublish-community repository and the new ezplatform repository in order to re-start community builds for the 5.x branch we are creating this issue.

Goal: Clarify the differences between the older ezpublish-community repository and the new ezplatform repository in repository README.md documentation.

To achieve this goal we will update the README.md documentation in each repository via separate pull requests to explain the main difference (today) between each repository is the inclusion or exclusion of legacy dependencies by default.

This pull request addresses the issue in question for this repository. 
Another pull request exists for the other repository. 
See issue ticket for alternate pull request links.

Please let us know how this finds you.

Thank you again for your continued support.

Cheers,
Brookins Consulting

### CODE REVIEW

**Comment by bdunogier** [comment]
I think it could/should be synthesized a bit. You don't need three titles for this imho.

What about this:

h4. eZ Publish / eZ Platform
This repository contains the eZ Publish 5 dual kernel. It integrates eZ Publish Legacy, unlike the next product generation, eZ Platform. It is mostly maintained for backwards compatibility.

eZ Platform, formerly eZ Publish 6, uses the same Symfony kernel than eZ Publish 5, but does not include the legacy application, nor the dependent libraries. This is where the new features are added.

**Comment by brookinsconsulting** [comment]
Hello @bdunogier

We have completed the changes requested and flattened.

Please let us know how this finds you.

Also what can be done to address and fix the broken travis testing for this repository?

Thank you again for your continued support.

Cheers,
Brookins Consulting

**Comment by andrerom** [comment]
+1

**Comment by bdunogier** [comment]
Thank you @brookinsconsulting.

**Comment by brookinsconsulting** [comment]
Hello,

Thank you for your continued support!

Cheers,
Brookins Consulting

**Pull request merged**
