### PR TITLE
Add missing /web/css and /web/js to .gitignore

### PR DESCRIPTION
**Pull request by purple52**
These folders are created by assets:install and therefore shouldn't be added to version control when created.

### CODE REVIEW

**Comment by bdunogier** [comment]
Thank you for your contribution, @purple52.

Looks good to me, +1, and the failure is indeed not yours. Would be cool if somebody could investigate this.

**Comment by bdunogier** [comment]
@crevillo has a point. assetic is indeed not required by ezpublish5. On the other hand, it is what the doc recommends, is it not ?

Both are fine with me, I'll let you guys discuss it :-)

**Comment by andrerom** [comment]
+0,5, *this brings us up to +2 ;)*

**Comment by crevillo** [comment]
so, if this is +2, I'm not against merging it. Devs could modify gitignore it they want :)

**Comment by purple52** [comment]
No longer required since this project is obsolete

**Pull request closed without merging**
