### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by ghost**
v2015.01 does not exist at this time

### CODE REVIEW

**Comment by andrerom** [comment]
Related: "Platform Reverts" #234

**Comment by andrerom** [comment]
INSTALL.md updated (well, reverted to how it was before [ezplatform](https://github.com/ezsystems/ezplatform) commits)

**Comment by brookinsconsulting** [comment]
ping @andrerom 

Can this PR now be closed, since it no longer applies? What must be done to close this?

Cheers,
Brookins Consulting

**Comment by andrerom** [comment]
yes

**Pull request closed without merging**
