### PR TITLE
[Just for testing] EZP-23927: moved http-cache-bundle down to 1.1.1

### PR DESCRIPTION
**Pull request by bdunogier**
> [EZP-23927](https://jira.ez.no/browse/EZP-23927)

It seems that http-cache-bundle 1.2 causes issues with User-Hash based variations. Downgrading to 1.1.1 fixes the issue on my setup. Let's see what Travis says.

### CODE REVIEW

**Comment by bdunogier** [comment]
Fails with an error about site packages not being listed correctly...

A bit baffled. Need to reset my instance to try it here, and with the very touchy wizard that expects _exactly_ the same steps, it is a tiny bit tedious :(

**Comment by bdunogier** [comment]
Seems to pass now. The error is probably a timeout one. I'm adding a script that pre-fetches the packages using wget.

**Comment by joaoinacio** [comment]
@bdunogier:
Looks good, perhaps however separate the packages prefetch into its own JIRA and/or PR?

**Comment by bdunogier** [comment]
Yes, it won't be merged this way, don't worry :-)

But I have an issue with basename on Travis it seems... it doesn't like the `--suffix` / `-s` option.

**Comment by bdunogier** [comment]
@lolautruche is working on a proper fix.

**Pull request closed without merging**
