### PR TITLE
[EZP-24709] Enable Symfony VarDumper in Kernel for improved debugging

### PR DESCRIPTION
**Pull request by janit**
Load VarDumper Bundle for an improved debugging experience out-of-the-box.

### CODE REVIEW

**Comment by andrerom** [comment]
+1, thanks @janit

**Comment by gggeek** [comment]
Does it have to be declared as well in composer.json or not?

**Comment by andrerom** [comment]
afaik no, it is bundled as of 2.6 or 2.7

**Comment by andrerom** [comment]
you can always check that here btw:
https://github.com/symfony/symfony/blob/2.6/composer.json#L32

**Comment by gggeek** [comment]
yup, I was just too lazy to check the composer.json of all dependencies... my bad

**Pull request merged**
