### PR TITLE
Implement EZP-23993: Clarify and document how security issues should be reported

### PR DESCRIPTION
**Pull request by glye**
https://jira.ez.no/browse/EZP-23993

Ref ezsystems/ezpublish-kernel#1201

### CODE REVIEW

**Comment by pspanja** [comment]
+1, probably safe to assume that Travis failure is unrelated :)

**Comment by yannickroger** [comment]
+1

**Comment by andrerom** [comment]
+1

**Comment by glye** [comment]
Appended dots as suggested in other PR.

**Pull request merged**
