### PR TITLE
EZP-24150: Implement privacy cookie law in demo bundle

### PR DESCRIPTION
**Pull request by clash82**
Link to Jira task: https://jira.ez.no/browse/EZP-24150

More info: https://github.com/ezsystems/DemoBundle/pull/149

### CODE REVIEW

**Comment by andrerom** [comment]
+1

**Comment by clash82** [comment]
+1 :)

**Comment by andrerom** [comment]
On second look this should be on the ezplatform repo.

I'll update BehatBundle and DemoBundle to use that one for behat testing, already done on kernel.

**Comment by clash82** [comment]
Added to ezplatform.

https://github.com/ezsystems/ezplatform/pull/10

**Comment by andrerom** [comment]
ok.

@bdunogier Any pros/cons about adding it here? (I'm neutral, I guess we can add it)

**Comment by clash82** [comment]
DemoBundle requires PrivacyCookieBundle to work correctly so... imo it should be here also.
ping @bdunogier

**Comment by andrerom** [comment]
I agree, and he is on vacation so will merge for now and if we decide to put it out it will be one of the reverts in the separate pr here.

**Comment by clash82** [comment]
Great, thanks.

**Pull request merged**
