### PR TITLE
Implement EZP-23873: Allow fonts to be pulled

### PR DESCRIPTION
**Pull request by waldermort**
Enable nginx to serve font files without sending the route through the app.

Link: https://jira.ez.no/browse/EZP-23873

### CODE REVIEW

**Comment by andrerom** [comment]
+1, ping @yannickroger

**Comment by yannickroger** [comment]
Looks good +1
Did you test it @waldermort ?

**Comment by waldermort** [comment]
@yannickroger  I don't have access to nginx, so no way of testing it. But, to be honest, it's only a set of conditions.

**Comment by yannickroger** [comment]
I am running nginx localy, so I'll test it before merging.

**Comment by andrerom** [comment]
@yannickroger Could you also pass issue to QA when you add merge comment on issue?

**Comment by yannickroger** [comment]
of course I'll take care of it.

**Comment by yannickroger** [comment]
Thanks @waldermort

**Pull request merged**
