### PR TITLE
Use global namespaces in EzPublishKernel

### PR DESCRIPTION
**Pull request by joaoinacio**
This replaces #172 , which seems no longer updated.

### CODE REVIEW

**Comment by brookinsconsulting** [comment]
@joaoinacio 

You beat me to it again :D Thank you very much for picking up and completing this work!

Cheers,
Brookins Consulting

**Comment by andrerom** [comment]
+1 from my side

**Comment by joaoinacio** [comment]
(On a side note, is there an issue for the failing test?
Looks like a problem with places image thumbnail/alt text )

**Comment by andrerom** [comment]
It has nothing to do with this PR, it is related to BDD made by @clash82, it might not be compatible with how 5.x with legacy stack renders images??? Maybe @bdunogier knows.

**Comment by lolautruche** [comment]
+1

**Comment by lolautruche** [comment]
Waiting for feedback from @bdunogier before merging this one.

**Comment by bdunogier** [comment]
Hmmm, the test should work independently of the version. Maybe the images are just broken in the install ? :-)

**Pull request merged**
